### ISSUE TITLE
Pending liabilities task should only ignore tax type not found errors

### ISSUE THREAD

**Issue by siphomateke** [siphomateke/zra-helper#13]
*Originally reported by* **Robert Henson (Bitbucket: [rahensonzam](https://bitbucket.org/rahensonzam), GitHub: [rahensonzam](https://github.com/rahensonzam))**

----------------------------------------

Under Pending Liabilities task if all the tabs have any other error other than 'taxtype not found' error, that should turn the parent task red. In other words, if there is one green subtask or one 'taxtype not found' error leave the parent task green.

----------------------------------------
- Bitbucket: https://bitbucket.org/nextgensparx/zra-helper/issue/13

**Comment by nextgensparx** [comment]
Closed by a79775bbfc047ae5d8e4f7c8750a1176fbb0ee48

**Comment by rahensonzam** [comment]
Check this under v1.1.0

It seems to have reverted.
