### ISSUE TITLE
Add clients that fail during runtime to the output

### ISSUE THREAD

**Issue by rahensonzam** [siphomateke/zra-helper#33]
Related to / merge with feature #28 

Add clients that fail during runtime to the output, as blank ones, for the same reason as #28

**Comment by rahensonzam** [comment]
Under v1.1.0

For these two errors

- Login "Timed out waiting for tab to load."
- and "Please check your internet and try again."
- and possibly any other root tasks that fail.

those clients are not added to the output.

**Comment by siphomateke** [comment]
@rahensonzam Does this only happen when the errors are from login and logout?
