### ISSUE TITLE
Mark clients in the output that partially complete

### ISSUE THREAD

**Issue by rahensonzam** [siphomateke/zra-helper#36]
Mark in the output the individual tax types for a client that error, to the right.
eg
```
"Henson","ITX","0.00","0.00","0.00","0.00"
"","VAT","0","0","0","0","!"
"","PAYE","0","0","0","0"
"","TOT","","","",""
"","WHT","0","0","0","0","!"
"","PTT","","","",""
"","MINROY","","","",""
"","TLEVY","","","",""
```
then I don't have to mark them afterwards
and if the internet is very slow I can combine multiple partials.

**Comment by siphomateke** [comment]
I assume you mean I should put an exclamation mark to the right of each tax type that experiences an error **except** when that error is 'tax type not found'?
