### ISSUE TITLE
Some receipts don't download and timeout

### ISSUE THREAD

**Issue by rahensonzam** [siphomateke/zra-helper#39]
On occasion, certain receipts will load and render but not download, then they just timeout. So that's timeout working.

I would guess but don't know that it is because it fails to register that these receipts have completed loading.

**Comment by siphomateke** [comment]
Possibly related, this error shows up in receipt tabs that take a long time to load:

> ePaymentController.htm:5 Active resource loading counts reached a per-frame limit while the tab was in background. Network requests will be delayed until a previous loading finishes, or the tab is brought to the foreground. See https://www.chromestatus.com/feature/5527160148197376 for more details

**Comment by siphomateke** [comment]
@rahensonzam Please test this with a really high timeout. Perhaps even an infinite timeout. The extension should eventually register that the tab has loaded if the issue is that chrome is rate-limiting network requests.

**Comment by siphomateke** [comment]
This has gotten significantly worse recently. Receipts now timeout almost 100% of the time.
