### ISSUE TITLE
Surplus pages spawn, fill up max tabs and halt execution

### ISSUE THREAD

**Issue by rahensonzam** [siphomateke/zra-helper#95]
v1.3.1

Sometimes tabs that timeout such as the main page or the login page don't close and then it seems there is one per client until it fills up all the tab 'slots' then it just waits. If you close some it continues running.

Another page that I have seen multiple copies of is the "tax payer profile" page.

**Comment by siphomateke** [comment]
Related to #92

**Comment by rahensonzam** [comment]
v1.3.1
Login pages don't seem to close at all if they timeout

**Comment by siphomateke** [comment]
@rahensonzam To clarify, if a login tab is opened but never actually loads anything, it is never closed?

**Comment by siphomateke** [comment]
Fixed in v1.4.0
