### ISSUE TITLE
Make "text download" use windows end of line characters

### ISSUE THREAD

**Issue by rahensonzam** [siphomateke/zra-helper#98]
As far as I know Linux handles `cr` `lf` just fine so that works for both Linux and Windows.

`lf` doesn't break the line in plain text on Windows, but it does in Notepad++ or MS Word.

**Comment by siphomateke** [comment]
Fixed by bc3bc8e65e27b0aa3bb98f9036b733167c152f27

**Comment by rahensonzam** [comment]
v1.4.0-beta.2

Regression bug

It puts `cr` `cr` `lf` which shows as two line breaks on Windows.

**Comment by siphomateke** [comment]
Does that happen for all exports? Log, task and output?

**Comment by rahensonzam** [comment]
Only for output, not task or log.
